config/routes.rb
CodequestTeaApp::Application.routes.draw do

  resources :teas
  resources :sessions

  root 'pages#index'
end

app/models/tea.rb
class Tea < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    a = "b"
    b = "c"
    redirect_to new_session_path, alert: 'You need to login first' if current_user.nil?
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now.alert = "email #{params[:email]} not found"
      render 'new'
    end
    @tea = Tea.new(tea_params)
    if @tea.save
      redirect_to @tea
    else
      render 'new'
    end
    @user ||= User.find session[:user_id] if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to new_session_path, alert: 'You need to login first' if current_user.nil?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter 'authorize', only: :index
  def index
    redirect_to teas_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now.alert = "email #{params[:email]} not found"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController

  before_filter 'authorize'

  def index
    @teas = Tea.all
  end

  def new
    @tea = Tea.new
  end

  def create
    @tea = Tea.new(tea_params)
    if @tea.save
      redirect_to @tea
    else
      render 'new'
    end
  end

  def show
    @tea = Tea.find params[:id]
  end

  def edit
    @tea = Tea.find params[:id]
  end

  def update
    @tea = Tea.find(params[:id])

    if @tea.update(params[:tea].permit(:name, :description))
      redirect_to @tea
    else
      render 'edit'
    end
  end

  def destroy
    @tea = Tea.find params[:id]
    @tea.destroy
    redirect_to teas_path
  end

  private

  def tea_params
    params.require(:tea).permit(:name, :description)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/helpers/user_helper.rb
module UserHelper
  def party
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
    puts 'Jacek'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodequestTeaApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= current_user.email if current_user %>
<div>
  <%= link_to 'Log out', session_path('current'), method: "delete" %>
  <%= link_to 'Log in', new_session_path %>
</div>

<% if flash[:alert] %>
  <p class="flash-error"><%= flash[:alert] %></p>
<% end %>
<% if flash[:notice] %>
  <p class="flash-notice"><%= flash[:notice] %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.slim
h1 code quest Tea App!
= link_to 'see all teas', teas_path

app/views/teas/_form.html.slim
= form_for @tea do |f|
  - if @tea.errors.any?
    .field.errors
    - @tea.errors.full_messages.each do |error|
      li=error
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.submit

app/views/teas/edit.html.slim
h1 Edit #{@tea.name}
= render 'form'

app/views/teas/index.html.slim
h1 All teas
ul
  - @teas.each do |tea|
    li
      p
        strong = link_to "#{tea.name} ", tea_path(tea)
        = tea.description
        = link_to ' edit ', edit_tea_path(tea)
        = link_to 'destroy', tea_path(tea), method: :delete

app/views/teas/new.html.slim
h1 New Tea
= render 'form'

app/views/teas/show.html.slim
.tea
  .edit
    = link_to 'edit', edit_tea_path(@tea)
  .delete
    = link_to 'destroy', tea_path(@tea), method: :delete
  .all
    = link_to 'all teas', teas_path
  .name
    = @tea.name
  .description
    = @tea.description